[package]
name = "envz"
version = "0.1.0"
edition = "2024"
description = "A Rust library for persistently reading and modifying Windows environment variables via the registry"
repository = "https://github.com/Delphier/envz"
homepage = "https://github.com/Delphier/envz"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "2.0.20"
windows = { version = "0.62.2", features = ["Win32"] }
windows-registry = "0.6.1"
windows-result = "0.4.1"
